services:
  web:
    image: denniskasper.com
    build:
      context: ./
      target: dev
    container_name: web
    command: pnpm dev-watch
    ports:
      - '4321:4321'
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
