version: '3.8'

services:
  web:
    build:
      context: ./
      target: dev
    container_name: web
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev-compose
    ports:
      - '4321:4321'
    environment:
      NODE_ENV: development
