name: CI/CD

on:
  push:
    branches: main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build production bundle
        run: pnpm build

      - name: Archive dist folder
        run: tar -czf dist.tar.gz ./dist

      - name: Copy files via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: dist.tar.gz
          target: /var/www/denniskasper.com/html
          rm: true

      - name: Extract archive and move & delete files
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            tar -zxvf /var/www/denniskasper.com/html/dist.tar.gz -C /var/www/denniskasper.com/html
            mv /var/www/denniskasper.com/html/dist/* /var/www/denniskasper.com/html
            rm -rf /var/www/denniskasper.com/html/dist.tar.gz /var/www/denniskasper.com/html/dist
