name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Build production bundle
        run: npm run build
      - name: Copy files
        run: |
          rm -r /var/www/denniskasper.com/html/*
          cp -a ./dist/* /var/www/denniskasper.com/html/
